from_latest_tag = false
ignore_merge_commits = true
tag_prefix = "v"
branch_whitelist = [
  "main",
  "release/**"
]
pre_bump_hooks = [
    "poetry version {{version}}",
    "poetry lock --no-update",
]
post_bump_hooks = [
    "git push origin v{{version}}",
    "git push",
]

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "carbon-guard"
owner = "armakuni"
authors = []

[bump_profiles]