name: Pipeline

on:
  push: ~
  pull_request: ~
  workflow_dispatch:

jobs:
  validate-pipeline:
    uses: armakuni/github-actions/.github/workflows/lint-pipeline.yml@11f2a137ef0371b345e6ef3eb19826cd1250bb06 # v0.19.6

  validate-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./
        with:
          max_carbon_intensity: 10000

  validate-python:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: specdown/setup-specdown-action@3479a13e83a0f2f3adacfd09d88ad6d660e01aee # v0.2.32
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
      with:
        version: "latest"
        enable-cache: true
    - run: make lint
    - run: make test
    - run: |
        echo "$CO2_SIGNAL_API_KEY" > .co2_api_key
        make integration
      env:
        CO2_SIGNAL_API_KEY: ${{secrets.CO2_SIGNAL_API_KEY}}
      if: github.ref == 'refs/heads/main'
    - name: Spot vunerable dependencies
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        exit-code: '1'
        scan-ref: .

  all-tests-succeeded:
    needs: [ validate-pipeline, validate-action, validate-python ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "All tests succeeded"
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [ all-tests-succeeded ]
    name: Release
    permissions:
      contents: write
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
        with:
          version: "latest"
          enable-cache: true
      - name: Cocogitto release
        id: release
        continue-on-error: true
        uses: oknozor/cocogitto-action@c7a74f5406bab86da17da0f0e460a69f8219a68c # v3.11
        with:
          release: true
      - name: Generate Changelog
        if: steps.release.outputs.version != ''
        run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

      - name: Upload github release
        if: steps.release.outputs.version != ''
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}

  pypi-publish:
    needs: [ release ]
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      url: https://pypi.org/project/carbon-guard/
      name: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ needs.release.outputs.version }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
        with:
          version: "latest"
          enable-cache: true
      - name: Install dependencies
        shell: bash
        run: uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
